[package]
name = "hc-256"
version = "0.0.1"
authors = ["Eric McCorkle <eric@metricspace.net>"]
license = "MIT OR Apache-2.0"
description = "HC-256 Stream Cipher"
repository = "https://github.com/RustCrypto/stream-ciphers"
keywords = ["crypto", "stream-cipher", "trait"]
categories = ["cryptography", "no-std"]

[dependencies]
block-cipher-trait = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
stream-cipher = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
zeroize = { version = "1", optional = true }

[dev-dependencies]
#stream-cipher = { version = "0.3", features = ["dev"] }
#block-cipher-trait = { version = "0.6", features = ["dev"] }

[badges]
maintenance = { status = "experimental" }
travis-ci = { repository = "RustCrypto/stream-ciphers" }
