[package]
name = "chacha20"
version = "0.2.3"
authors = ["RustCrypto Developers"]
license = "Apache-2.0 OR MIT"
description = """
The ChaCha20 stream cipher (RFC 8439) implemented using traits from the
RustCrypto stream-cipher crate.
"""
repository = "https://github.com/RustCrypto/stream-ciphers"
keywords = ["crypto", "stream-cipher", "xchacha20"]
categories = ["cryptography", "no-std"]
readme = "README.md"

[badges]
travis-ci = { repository = "RustCrypto/stream-ciphers" }

[dependencies]
byteorder = { git = "https://github.com/mesalock-linux/byteorder-sgx" }
stream-cipher = { git = "https://github.com/mesalock-linux/rustcrypto-traits-sgx" }
salsa20-core = { version = "0.2", path = "../salsa20-core" }
rand_core = { version = "0.5", optional = true }

[dev-dependencies]
#stream-cipher = { version = "0.3", features = ["dev"] }
#criterion = "0.3"
#criterion-cycles-per-byte = "0.1"

[features]
default = ["xchacha20"]
legacy = []
xchacha20 = []
zeroize = ["salsa20-core/zeroize"]
rng = ["rand_core"]

[[bench]]
name = "chacha20"
harness = false

[package.metadata.docs.rs]
all-features = true
